print('Введите координаты двух точек')
x1=float(input('Введите х1: '))
y1=float(input('Введите y1: '))
x2=float(input('Введите х2: '))
y2=float(input('Введите y2: '))
result_ = round(((x2-x1)**2+(y2-y1)**2)**0.5,3)
print(result_)
